# Use this docker-compose file to host the site locally
version: "3.7"
services:
  nginx:
    container_name: ${PROJECT_NAME}
    image: ${NGINX_CONTAINER}
    expose:
      - 80
      - 9222
    depends_on:
      - php
      - mysql
    networks:
      - demigod
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
      - "9222:9222"
    env_file:
      - .envrc
    environment:
      - PROJECT_NAME=${PROJECT_NAME}

  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PHP_CONTAINER}
    expose:
      - "9000"
    volumes:
      - ".:/var/www"
      - "$HOME/.terminus/cache:/root/.terminus/cache:cached"
      - type: bind
        source: $HOME/.ssh
        target: /root/.ssh
        read_only: true
    networks:
      - demigod
    env_file:
      - .envrc
    environment:
      - BACKUP_FILE_NAME=${PROJECT_NAME}.sql.gz
      - DATABASE_NAME=drupal8
      - PROJECT_NAME=${PROJECT_NAME}

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: ${MYSQL_CONTAINER}
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      - demigod
    expose:
      - "3306"
    ports:
      - "33067:3306"
    env_file:
      - .envrc
    healthcheck:
      test: [
          "CMD",
          "mysqladmin",
          "ping",
          "--user=${MYSQL_USER}",
          "--password=${MYSQL_PASSWORD}",
          "--host=localhost"
      ]
      retries: 10
      interval: 15s
      timeout: 5s

  redis:
    # Generic redis instance
    container_name: ${PROJECT_NAME}-redis
    image: redis
    networks:
      - demigod
    expose:
      - "6379"

  solr:
    container_name: ${PROJECT_NAME}-solr
    image: ${SOLR_CONTAINER}
    depends_on:
      - zk
    networks:
      - demigod
    environment:
      ZK_HOST: "zk:2181"
    entrypoint:
      - "bash"
      - "-c"
      - "/opt/docker-solr/scripts/solr-create -c ${PROJECT_NAME} -d /opt/search_api_solr/jump-start/solr8/cloud-config-set"
    expose:
      - "8983"
    ports:
      - "8983:8983"

  zk:
    container_name: ${PROJECT_NAME}-zk
    image: zookeeper
    networks:
      - demigod
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
      ZOO_4LW_COMMANDS_WHITELIST: "mntr, conf, ruok"
      SERVER_JVMFLAGS: "-Xms2048m -Xmx2048m"
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
    expose:
      - "2181"
    ports:
      - "2181:2181"

  zk-ui:
    container_name: ${PROJECT_NAME}-zk-ui
    image: elkozmon/zoonavigator
    depends_on:
      - zk
    networks:
      - demigod
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      HTTP_PORT: "9000"
      AUTO_CONNECT_CONNECTION_STRING: "zk:2181"

volumes:
  web: { }
  initmysql: { }
  data:
networks:
  demigod:
